## metrics_path defaults to '/metrics'
## scheme defaults to 'http'.

scrape_configs:
  - job_name: 'factorio-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['exporter:9100']
